-- STATIC TABLES
CREATE TABLE GYMS(
    GYM VARCHAR(50) PRIMARY KEY
);

CREATE TABLE WALL_TYPES(
    WALL_TYPE VARCHAR(50) PRIMARY KEY
);

CREATE TABLE BOULDER_TYPES(
    BOULDER_TYPE VARCHAR(50) PRIMARY KEY
);

CREATE TABLE COLORS(
    COLOR VARCHAR(50) PRIMARY KEY
);

CREATE TABLE HOLD_TYPES(
    HOLD_TYPE VARCHAR(50) PRIMARY KEY
);

CREATE TABLE GRADES(
    GRADE VARCHAR(3) PRIMARY KEY
);

CREATE TABLE BURNS(
    BURN_NUMBER VARCHAR(5) PRIMARY KEY
);

-- DYNAMIC TABLES
CREATE TABLE USERS(
    USERNAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(60),
    SALT VARCHAR(16)
);

CREATE TABLE SENDS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GRADE VARCHAR(3),
    COLOR VARCHAR(50),
    HOLD_TYPE VARCHAR(50),
    GYM VARCHAR(50),
    WALL_TYPE VARCHAR(50),
    BOULDER_TYPE VARCHAR(50),
    BURN_NUMBER VARCHAR(5),
    SESSION_DATE DATE,
    USERNAME varchar(50)
);

ALTER TABLE SENDS ADD CONSTRAINT FK_SENDS_GRADE FOREIGN KEY (GRADE) REFERENCES GRADES(GRADE);
ALTER TABLE SENDS ADD CONSTRAINT FK_SENDS_COLOR FOREIGN KEY (COLOR) REFERENCES COLORS(COLOR);
ALTER TABLE SENDS ADD CONSTRAINT FK_SENDS_HOLD_TYPE FOREIGN KEY (HOLD_TYPE) REFERENCES HOLD_TYPES(HOLD_TYPE);
ALTER TABLE SENDS ADD CONSTRAINT FK_SENDS_GYM FOREIGN KEY (GYM) REFERENCES GYMS(GYM);
ALTER TABLE SENDS ADD CONSTRAINT FK_SENDS_WALL_TYPE FOREIGN KEY (WALL_TYPE) REFERENCES WALL_TYPES(WALL_TYPE);
ALTER TABLE SENDS ADD CONSTRAINT FK_SENDS_BOULDER_TYPE FOREIGN KEY (BOULDER_TYPE) REFERENCES BOULDER_TYPES(BOULDER_TYPE);
ALTER TABLE SENDS ADD CONSTRAINT FK_SENDS_BURN FOREIGN KEY (BURN_NUMBER) REFERENCES BURNS(BURN_NUMBER);
ALTER TABLE SENDS ADD CONSTRAINT FK_SENDS_USER FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME);