ALTER TABLE BURNS ADD COLUMN SORT_ID INT;

UPDATE BURNS SET SORT_ID = 1 WHERE BURN_NUMBER = 'FLASH';
UPDATE BURNS SET SORT_ID = 2 WHERE BURN_NUMBER = '1';
UPDATE BURNS SET SORT_ID = 3 WHERE BURN_NUMBER = '2';
UPDATE BURNS SET SORT_ID = 4 WHERE BURN_NUMBER = '3';
UPDATE BURNS SET SORT_ID = 5 WHERE BURN_NUMBER = '4';
UPDATE BURNS SET SORT_ID = 6 WHERE BURN_NUMBER = '5';
UPDATE BURNS SET SORT_ID = 7 WHERE BURN_NUMBER = '6-10';
UPDATE BURNS SET SORT_ID = 8 WHERE BURN_NUMBER = '11-19';
UPDATE BURNS SET SORT_ID = 9 WHERE BURN_NUMBER = '20+';